/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_manager_incremental_BsPatchNative */

#ifndef _Included_com_manager_incremental_BsPatchNative
#define _Included_com_manager_incremental_BsPatchNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_manager_incremental_BsPatchNative
 * Method:    bspatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_manager_incremental_BsPatchNative_bspatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
